In [128]:
import numpy as np
from sklearn import linear_model
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import Lasso, ElasticNet
from sklearn.model_selection import train_test_split
import itertools
from scipy.special import comb
from sklearn.model_selection import LeaveOneOut

In [6]:
data = np.genfromtxt('mystery.dat', delimiter=',')

In [7]:
data[:10]

array([[-1.14558, -1.29249,  0.84911, ...,  1.5532 , -1.42135,  1.19238],
       [ 1.38724, -1.00201, -0.3337 , ...,  0.81903,  0.39286, -3.44094],
       [ 1.47233,  0.8488 , -0.33866, ...,  0.08911, -1.72476,  3.75006],
       ..., 
       [ 0.30591,  0.6181 , -0.53558, ...,  0.58157,  1.7936 ,  0.89253],
       [ 0.98709,  0.28845, -0.60568, ...,  1.51293,  0.29517,  3.35149],
       [-1.79134, -0.86634, -0.11171, ..., -1.17257, -1.01425, -1.97817]])

In [9]:
X = data[:, np.arange(100)]
y = data[:, -1]
print(X[:3], y[:3])

[[-1.14558 -1.29249  0.84911  0.36008  0.26068  2.51167  2.31855  0.60805
   0.3428  -0.28903  0.70398  1.18534 -1.44321 -0.72979 -0.06026 -0.50449
  -0.3148   0.94552 -0.32453 -0.09248  0.84448  0.32551  0.57684 -0.12461
  -0.5531  -1.37074 -0.85719  0.05802  0.27486 -0.09269  0.28742 -1.29854
   0.66856  0.02223  0.28599 -0.28722  0.54304  0.67301 -0.67343  1.19857
   1.35595  1.53356 -0.61245  1.91698  1.89642  1.28004  0.60073 -0.37792
   0.34903  2.17043 -1.52004 -0.75143 -0.54607 -0.46285  0.28424  0.02458
  -2.31083 -0.43165  0.87581 -0.07552  0.66682  1.65492 -0.71924  1.39364
   0.5405   0.55335  1.00319 -0.76292 -0.26241 -1.32323 -0.15256 -0.30767
   0.37729  0.02091  1.05892 -0.30399  1.76204 -1.38097  0.96642 -0.34674
   0.92688 -1.05426 -0.50192  0.11954  0.97006  2.01984  0.00975  0.65729
  -1.01224  0.93274 -1.92116  0.16212 -0.60644  1.57021 -1.40166 -0.65263
  -0.08357  0.78098  1.5532  -1.42135]
 [ 1.38724 -1.00201 -0.3337   0.32802  0.1586  -0.5706  -0.05989  0.91503

In [31]:
y.shape

(101,)

In [214]:
def feature_subset_regression(x,y,flist):
    if len(flist) < 1:
        print("Need at least one feature")
        return
    for f in flist:
        if (f < 0) or (f > 100):
            print("Feature index is out of bounds")
            return
    regr = linear_model.LinearRegression()
    regr.fit(x[:,flist], y)
    y_pred = regr.predict(x[:,flist])
    return mean_squared_error(y, y_pred)

In [215]:

num_lines = int(comb(100, 3))
all_loss = np.zeros([num_lines, 3])
c = itertools.combinations(np.arange(100), 3)
count = 0
for i in c:
    loss = feature_subset_regression(X,y,list(i))
    all_loss[count, 0] = i[0]
    all_loss[count, 1] = i[1]
    all_loss[count, 2] = loss
    count += 1
# all_loss

In [72]:
np.argmin(all_loss[:, 2])

44655

In [212]:
comb(19, 10)

92378.0

In [93]:
c = itertools.combinations(np.arange(44), 43)
for i in c:
    print(i)

(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42)
(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 43)
(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 42, 43)
(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 41, 42, 43)
(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 40, 41, 42, 43)
(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 39, 40, 41, 42, 43)
(0, 1, 2, 3, 4, 5, 6, 

In [73]:
all_loss[44655]

array([ 10.        ,  16.        ,   5.86964778])

### split raw data

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [11]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(70, 100) (31, 100) (70,) (31,)


In [59]:
lamb = np.geomspace(0.01, 10.24, 11)
lamb

array([  1.00000000e-02,   2.00000000e-02,   4.00000000e-02,
         8.00000000e-02,   1.60000000e-01,   3.20000000e-01,
         6.40000000e-01,   1.28000000e+00,   2.56000000e+00,
         5.12000000e+00,   1.02400000e+01])

In [47]:
lamb_new = np.geomspace(0.04, 0.16, 11)
lamb_new

array([ 0.04      ,  0.04594793,  0.05278032,  0.06062866,  0.06964405,
        0.08      ,  0.09189587,  0.10556063,  0.12125733,  0.13928809,
        0.16      ])

### Use Lasso

In [60]:
for la in lamb_new:
    lasso_reg = Lasso(alpha=la)
    lasso_reg.fit(X_train, y_train)
    print('--------{}---------'.format(la))
#     print(lasso_reg.intercept_, lasso_reg.coef_)
    print(np.where(lasso_reg.coef_!=0)[0].shape)
    h = lasso_reg.predict(X_test)
    print(mean_squared_error(h, y_test))

--------0.04000000000000001---------
(52,)
2.22411046847
--------0.04594793419988143---------
(50,)
2.17065423078
--------0.05278031643091578---------
(49,)
2.11736477343
--------0.060628662660415916---------
(44,)
2.09838502942
--------0.06964404506368994---------
(38,)
2.1115817056
--------0.08000000000000003---------
(33,)
2.166995409
--------0.09189586839976281---------
(30,)
2.23430088194
--------0.10556063286183155---------
(27,)
2.3227910713
--------0.12125732532083186---------
(23,)
2.38393971333
--------0.13928809012737986---------
(23,)
2.39246261158
--------0.16---------
(23,)
2.42732745839


In [121]:
lasso_reg_new = Lasso(alpha=0.06)
lasso_reg_new.fit(X_train, y_train)
print(lasso_reg_new.intercept_, lasso_reg_new.coef_)

-0.141271914315 [  0.00000000e+00   8.77191621e-01   6.56719593e-01  -0.00000000e+00
   1.04413112e+00  -0.00000000e+00   9.88610166e-01  -1.61307607e-01
  -0.00000000e+00  -0.00000000e+00   8.48582639e-01   0.00000000e+00
   5.89122429e-01   3.81104732e-02  -1.34068445e-01  -8.01344666e-02
   9.33562238e-01  -0.00000000e+00   7.17510449e-01   1.08161258e-02
  -0.00000000e+00  -0.00000000e+00   8.78496334e-01   6.48877331e-02
  -0.00000000e+00  -0.00000000e+00  -0.00000000e+00  -0.00000000e+00
   5.47771184e-01   0.00000000e+00   0.00000000e+00   7.09319790e-03
   0.00000000e+00  -8.97244664e-03  -1.31301930e-02   0.00000000e+00
  -0.00000000e+00  -0.00000000e+00  -1.41106288e-01   0.00000000e+00
   0.00000000e+00   3.48020391e-02  -3.68044198e-03  -8.02438963e-02
   3.86653451e-02   5.87238517e-03  -0.00000000e+00  -4.17612445e-02
  -0.00000000e+00   1.87081368e-01   0.00000000e+00  -0.00000000e+00
   4.10068945e-04   4.58521471e-02  -0.00000000e+00   3.63852394e-01
   1.23693018e-01 

In [123]:
non_zero_index = np.where(lasso_reg_new.coef_!=0)[0]
non_zero_index[35]

77

In [88]:
lasso_reg_new.coef_[non_zero_index]

array([  8.77191621e-01,   6.56719593e-01,   1.04413112e+00,
         9.88610166e-01,  -1.61307607e-01,   8.48582639e-01,
         5.89122429e-01,   3.81104732e-02,  -1.34068445e-01,
        -8.01344666e-02,   9.33562238e-01,   7.17510449e-01,
         1.08161258e-02,   8.78496334e-01,   6.48877331e-02,
         5.47771184e-01,   7.09319790e-03,  -8.97244664e-03,
        -1.31301930e-02,  -1.41106288e-01,   3.48020391e-02,
        -3.68044198e-03,  -8.02438963e-02,   3.86653451e-02,
         5.87238517e-03,  -4.17612445e-02,   1.87081368e-01,
         4.10068945e-04,   4.58521471e-02,   3.63852394e-01,
         1.23693018e-01,   1.57613225e-03,   1.70775338e-01,
         2.64073045e-02,  -3.17086172e-02,   2.89053596e-01,
         1.56637506e-01,  -7.14855564e-02,  -1.75216830e-02,
        -2.81329446e-01,   7.22165866e-02,   9.40277853e-02,
        -1.99723131e-02,  -1.76595379e-02])

In [89]:
X_train_new = X_train[:, non_zero_index]
X_test_new = X_test[:, non_zero_index]

In [90]:
X_train_new.shape

(70, 44)

### Using reduced features to train again
- reduce one feature each time and calculate the MSE

In [193]:
non_zero_index = np.array([ 1,  2,  4,  6,  7, 10, 12, 14, 15, 16, 18, 19, 22, 28, 31, 47, 53,
       56, 68, 72, 81, 98])

In [211]:
print(non_zero_index)
print(non_zero_index.shape)

[ 1  2  4  6  7 10 12 14 15 16 18 19 22 28 47 53 56 72 98]
(19,)


In [195]:
loo = LeaveOneOut()
lamb_best = 0.06
def loo_train(non_zero_index, X_train=X_train, X_test=X_test, y_train=y_train, y_test=y_test, alpah=lamb_best):
    loss_all = []  # collect all loss
    inx_all = []  # collect all index
    for train_inx, other_inx in loo.split(non_zero_index):
        inx_all.append(non_zero_index[train_inx])
        X_train_new = X_train[:, non_zero_index[train_inx]]
        X_test_new = X_test[:, non_zero_index[train_inx]]
        lasso_reg = Lasso(alpha=alpah)
        lasso_reg.fit(X_train_new, y_train)
        # print('--------{}---------'.format(i))
        # print(lasso_reg.intercept_, lasso_reg.coef_)
        # print(np.where(lasso_reg.coef_!=0)[0].shape)
        y_pred = lasso_reg.predict(X_test_new)
        loss_all.append(mean_squared_error(y_pred, y_test))
    return loss_all, inx_all


In [196]:
loss_all, inx_all = loo_train(non_zero_index)
min_loss = np.min(loss_all)
print(min_loss)
inx_all[np.argmin(loss_all)]

0.936050614538


array([ 1,  2,  4,  6,  7, 10, 12, 14, 15, 16, 18, 19, 22, 28, 31, 47, 53,
       56, 68, 72, 98])

In [208]:
def exe_loo_training(non_zero_index, t=10, min_loss=3):
    for i in range(t):
        loss_all, inx_all = loo_train(non_zero_index)
        min_loss_current = np.min(loss_all)
        # print(min_loss_current)
        if min_loss_current < min_loss:
            non_zero_index = inx_all[np.argmin(loss_all)]
            min_loss = min_loss_current
            print(min_loss)
        else:
            return non_zero_index, min_loss
    return non_zero_index, min_loss         

In [209]:
min_loss = 0.936050614538
non_zero_index, min_loss = exe_loo_training(non_zero_index, t=10, min_loss=min_loss)

In [210]:
non_zero_index

array([ 1,  2,  4,  6,  7, 10, 12, 14, 15, 16, 18, 19, 22, 28, 47, 53, 56,
       72, 98])

In [200]:
lasso_reg_new2 = Lasso(alpha=0.06)
lasso_reg_new2.fit(X_train[:, non_zero_index], y_train)
print(lasso_reg_new2.intercept_, lasso_reg_new2.coef_)
y_pred_new = lasso_reg_new2.predict(X_test[:, non_zero_index])
print(mean_squared_error(y_pred_new, y_test))

-0.130799464303 [ 0.96005254  0.83596483  1.09046617  0.91854377 -0.23835816  0.97251783
  0.67965765 -0.19712617 -0.01979662  0.86144834  0.81763405  0.12342069
  0.9667611   0.71401249  0.         -0.15424712  0.05750512  0.16868784
  0.          0.10862077 -0.03720228]
0.936050614538


In [201]:
non_zero_index2 = np.where(lasso_reg_new2.coef_!=0)[0]
non_zero_index2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 15, 16, 17,
       19, 20], dtype=int64)

In [202]:
non_zero_index = non_zero_index[non_zero_index2]
non_zero_index

array([ 1,  2,  4,  6,  7, 10, 12, 14, 15, 16, 18, 19, 22, 28, 47, 53, 56,
       72, 98])